### ISSUE TITLE
util/extract_GO_assignments_from_Trinotate_xls.pl output nothing with warning

### ISSUE THREAD

**Issue by wangyugui** [Trinotate/Trinotate#8]
util/extract_GO_assignments_from_Trinotate_xls.pl output nothing with the warning:

```
#/usr/hpc-bio/Trinotate-3.0-git/util/extract_GO_assignments_from_Trinotate_xls.pl --Trinotate_xls /biowrk/trinotate/juglans.hybrid.mRNA/trinotate.xls -G --include_ancestral_terms
Total transcript entries: 117479
Found obo: /bio/hpc-bio/Trinotate-3.0-git/util/../PerlLib/obo/go-basic.obo.gz
Warning, cannot parse parent info: regulates ! regulates
Warning, cannot parse parent info: regulates ! regulates
#
```

The updated go-basic.obo.gz(data-version: releases/2016-06-25) have the same reuslt.

**Comment by brianjohnhaas** [comment]
Hi,

Are GO assigments included in the Trinotate report file (xls)?

~b

On Sat, Jun 25, 2016 at 11:46 PM, wangyugui <notifications@github.com>
wrote:

> util/extract_GO_assignments_from_Trinotate_xls.pl output nothing with the
> warning:
>
> #/usr/hpc-bio/Trinotate-3.0-git/util/extract_GO_assignments_from_Trinotate_xls.pl --Trinotate_xls /biowrk/trinotate/juglans.hybrid.mRNA/trinotate.xls -G --include_ancestral_terms
> Total transcript entries: 117479
> Found obo: /bio/hpc-bio/Trinotate-3.0-git/util/../PerlLib/obo/go-basic.obo.gz
> Warning, cannot parse parent info: regulates ! regulates
> Warning, cannot parse parent info: regulates ! regulates
> #
>
> The updated go-basic.obo.gz(2016) have the same reuslt.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Trinotate/Trinotate/issues/8>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX6I384UVEbpTyzLOsWBzJGVTvoW_ks5qPfX5gaJpZM4I-eqZ>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by wangyugui** [comment]
Hi.
GO assigments was included in the Trinotate report file (xls)

```
# grep GO /biowrk/trinotate/juglans.hybrid.mRNA/trinotate.xls |head -n 2
TRINITY_DN1354_c0_g1    TRINITY_DN1354_c0_g1_i1 CALS9_ARATH^CALS9_ARATH^Q:1-282,H:1797-1890^81.915%ID^E:6.28e-50^RecName: Full=Callose synthase 9;^Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta; Spermatophyta; Magnoliophyta; eudicotyledons; Gunneridae; Pentapetalae; rosids; malvids; Brassicales; Brassicaceae; Camelineae; Arabidopsis       .       .       .       .       .       .       .       ENOG410XQ8V^synthase        KEGG:ath:AT3G07160`KO:K11000    GO:0000148^cellular_component^1,3-beta-D-glucan synthase complex`GO:0016021^cellular_component^integral component of membrane`GO:0003843^molecular_function^1,3-beta-D-glucan synthase activity`GO:0006075^biological_process^(1->3)-beta-D-glucan biosynthetic process`GO:0071555^biological_process^cell wall organization`GO:0008360^biological_process^regulation of cell shape .       .       .
TRINITY_DN1525_c0_g2    TRINITY_DN1525_c0_g2_i1 P2C27_ARATH^P2C27_ARATH^Q:2-187,H:133-194^79.032%ID^E:3.62e-26^RecName: Full=Probable protein phosphatase 2C 27;^Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta; Spermatophyta; Magnoliophyta; eudicotyledons; Gunneridae; Pentapetalae; rosids; malvids; Brassicales; Brassicaceae; Camelineae; Arabidopsis .       .       .       .       .       .       .   COG0631^Phosphatase     KEGG:ath:AT2G33700`KO:K14803    GO:0005737^cellular_component^cytoplasm`GO:0005634^cellular_component^nucleus`GO:0046872^molecular_function^metal ion binding`GO:0004722^molecular_function^protein serine/threonine phosphatase activity`GO:0061416^biological_process^regulation of transcription from RNA polymerase II promoter in response to salt stress`GO:0009737^biological_process^response to abscisic acid`GO:0009409^biological_process^response to cold`GO:0009651^biological_process^response to salt stress`GO:0009414^biological_process^response to water deprivation .       .       .
#
```

**Comment by wangyugui** [comment]
I'm very sorry that this was a usage mistake.

extract_GO_assignments_from_Trinotate_xls.pl  is OK.

**Comment by wangyugui** [comment]
I had a mistake that caused no  GO assigments was included in the Trinotate report file (xls), and then there was  no output in util/extract_GO_assignments_from_Trinotate_xls.pl.

With the mistake was fixed, I forgot to check the output of util/extract_GO_assignments_from_Trinotate_xls.pl again.

I'm sorry.

**Comment by brianjohnhaas** [comment]
no problem at all.  Glad it's working now!

~b

On Mon, Jun 27, 2016 at 12:19 PM, wangyugui <notifications@github.com>
wrote:

> I had a mistake that caused no GO assigments was included in the Trinotate
> report file (xls), and then there was no output in
> util/extract_GO_assignments_from_Trinotate_xls.pl.
>
> With the mistake was fixed, I forgot to check the output of
> util/extract_GO_assignments_from_Trinotate_xls.pl again.
>
> I'm sorry.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Trinotate/Trinotate/issues/8#issuecomment-228796133>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX1kPPWIGbbpj7rvKfcBjhTvncubnks5qP_gjgaJpZM4I-eqZ>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by maoshigua** [comment]
Hi,
when i use Trinotate to generate trinotate_annotation_report.xls (i only want to perform the GO test for those genes identified in differential expression analysis),I only load transcripts and coding regions, and blastx transcript hits (and no others). Then i did get trinotate_annotation_report.xls, but GO assigments were not included. How i can get GO assigments in the final trinotate_annotation_report.xls? Any possible problems?

Thank you very much.

Best wishes

Xiuguang Mao

**Comment by wangyugui** [comment]
Hi,Xiuguang Mao

At least search result of Pfam need to be loaded to assign GO.

**Comment by brianjohnhaas** [comment]
It's probably a database incompatibility issue. Be sure to search the exact versions of pfam and swissprot that are indicated on the software web documentation on github.  Also be sure to use the corresponding Trinotate boilerplate SQLite database.  Everything is located in the same directory.  I can post the link later if you can't find it.

Best,

-Brian
(by iPhone)

**Comment by maoshigua** [comment]
Hi,
Thanks a lot. When i load blastp hits, it works now

Best wishes,

Mao
